openapi: '3.0.2'
info:
  title: RESTful EPP
  version: '1.0'
servers:
  - url: https://api.example.nl/repp/v1/
paths:
  /domains/{id}:
    get:
      parameters:
      - name: id
        in: path
        required: true
      responses:
          '200':
            description: OK
